project:
  type: website
  output-dir: docs

website:
  title: "Learn Hugging Face ðŸ¤—"
  favicon: images/learn-hf-favicon.png
  image: https://huggingface.co/datasets/mrdbourke/learn-hf-images/resolve/main/misc/learn_hf_cover_image.png
  description: "Practical hands-on machine learning tutorials using the Hugging Face ecosystem."
  site-url: https://www.learnhuggingface.com
  repo-url: https://github.com/mrdbourke/learn-huggingface 
  issue-url: https://github.com/mrdbourke/learn-huggingface/issues 
  reader-mode: true
  back-to-top-navigation: true 
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: extras/setup.md
        text: Setup
      - href: extras/glossary.md
        text: Glossary
    tools:
      - icon: github
        href: https://github.com/mrdbourke/learn-huggingface
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Natural Language Processing (NLP)"
        contents:
          - href: notebooks/hugging_face_text_classification_tutorial.ipynb
            text: Text Classification
  page-footer: 
    right:
      - icon: globe
        href: https://www.mrdbourke.com
      - icon: github
        href: https://github.com/mrdbourke/learn-huggingface
      - icon: youtube 
        href: https://www.youtube.com/channel/UCr8O8l5cCX85Oem1d18EezQ 
      - icon: twitter-x
        href: https://twitter.com/mrdbourke
      - icon: linkedin
        href: https://www.linkedin.com/in/mrdbourke/
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



